# Generated by Django 5.2.2 on 2025-06-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
