# Generated by Django 5.2.2 on 2025-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_admin_delete_user_remove_song_audio_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
