# Generated by Django 5.2.2 on 2025-06-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_song_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='playlist',
        ),
    ]
